# Generated by Django 3.2.9 on 2021-11-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_notice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='id',
        ),
        migrations.AlterField(
            model_name='notice',
            name='noticeID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
